### ISSUE TITLE
provide full documentation of MLN analysis, with all sub-functions

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#266]
The `get_MLN` method of the `PhyBo` class has a docstring which for the `glm` parameter gives the cryptic description

```
glm : str
    The dictionary key for the gain-loss-model.
```

Giving it a random string results in

```
>>> p.get_MLN("x")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/vol/home/kaipingga/Analysis/lingpy/lingpy/compare/phylogeny.py", line 2055, in get_MLN
    scenarios = self.gls[glm]
KeyError: 'x'
```

because

```
>>> p.gls
{}
```

**Comment by LinguList** [comment]
This is a documentation issue, right? We have as a standard the following value structure: w-2-1 means "weighted" model with gain=2 and loss=1. There are others, but they are basically obsolete, and I wouldn't touch any other methods than those based on weights.

**Comment by LinguList** [comment]
The info is in detail here:

* http://lingpy.org/reference/lingpy.compare.html#lingpy.compare.phylogeny.PhyBo.get_GLS

**Comment by LinguList** [comment]
And here's a howto, showing a bit more of how to use mln (there are more):

https://gist.github.com/LinguList/7481097

**Comment by Anaphory** [comment]
Yep, it's a documentation thing. I'm trying to take shortcuts again.

**Comment by Anaphory** [comment]
Following the apparent steps when looking at `dir(PhyBo)` etc.:

    >>> p.get_GLS()
    |++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++|
    2016-10-20 12:49:25,205 [INFO] Successfully calculated Gain-Loss-Scenarios.
    2016-10-20 12:49:25,206 [INFO] Writing GLS data to file... 
    2016-10-20 12:49:25,245 [INFO] Data has been written to file </vol/home/kaipingga/Analysis/tap-aligned.tsv_phybo/gls/tap-aligned.tsv-w-1-1.gls>.
    2016-10-20 12:49:25,246 [INFO] Average Number of Origins: 1.99
    2016-10-20 12:49:25,252 [INFO] Data has been written to file </vol/home/kaipingga/Analysis/tap-aligned.tsv_phybo/stats/tap-aligned.tsv-w-1-1>.
    >>> p.get_MLN("w-1-1")
    2016-10-20 12:50:07,997 [INFO] Calculated primary graph.
    2016-10-20 12:50:07,997 [INFO] Inferring lateral edges...
    |++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++|
    2016-10-20 12:50:08,498 [INFO] Writing graph to file...
    2016-10-20 12:50:08,551 [INFO] Data has been written to file </vol/home/kaipingga/Analysis/tap-aligned.tsv_phybo/mln-w-1-1.gml>.
    2016-10-20 12:50:08,552 [INFO] Writing Inferred Lateral Events to file...
    2016-10-20 12:50:08,575 [INFO] Data has been written to file </vol/home/kaipingga/Analysis/tap-aligned.tsv_phybo/ile-w-1-1.csv>.
    2016-10-20 12:50:08,579 [INFO] Data has been written to file </vol/home/kaipingga/Analysis/tap-aligned.tsv_phybo/node.label.NA>.
    2016-10-20 12:50:08,596 [INFO] Data has been written to file </vol/home/kaipingga/Analysis/tap-aligned.tsv_phybo/taxa-w-1-1.stats>.
    2016-10-20 12:50:08,596 [INFO] Wrote node degree distributions to file.
    2016-10-20 12:50:08,706 [INFO] Data has been written to file </vol/home/kaipingga/Analysis/tap-aligned.tsv_phybo/edge-w-1-1.stats>.
    2016-10-20 12:50:08,706 [INFO] Wrote edge-weight distributions to file.
    2016-10-20 12:50:23,415 [INFO] Wrote list of edges per taxa to file.
runs fine, but then

    >>> p.plot_MLN("w-1-1")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/vol/home/kaipingga/Analysis/lingpy/lingpy/compare/phylogeny.py", line 3376, in plot_MLN
        if node in self.acs[glm]:
    KeyError: 'w-1-1'
fails with an error that is again not expected from the docstring.

**Comment by LinguList** [comment]
what is recommended is to use the variable best_mode:
p.plot_MLN(p.best_model).

I mean, you could just check the keys of p.acs, to see which models have been calculated, right?

**Comment by LinguList** [comment]
Just changed this issue name, as I don't want to stick to the little details here. I agree we need some bigger howto, for the meantime, however, just send me an example of your data, to understand what you want to do, so we can make that into a howto, or have a look at the commands given in the publications accompanying MLN (there are always full code-examples, which should all be back-compatible).

**Comment by Anaphory** [comment]
In terms of what I want, I think the comments above show that I found the important steps – I managed to produce a `MLN` and plot it (see #269)

Beyond that, I first need to settle on a reasonable data set and tree algorithm, because currently I'm
 - Treating reconstructed proto-forms precisely as any other language data
 - Mixing automatically cognate-guessed data and manual overrides from manual cognate coding (which also means some cognate sets have an artifical split between “Languages we got earlier and have already cognate-coded” and “languages we got later and haven't”)
 - Not paying attention to some languages being orthographic variants of others
 - Getting a tree that is quite bad out of the `__init__` for these reasons and possibly others.

Once I have these things sorted (in particular the methodological problems with awful data), I'll be happy to go for writing the next bits up explicitly and understandably to create a howto/tutorial for MLNs.

**Comment by LinguList** [comment]
super. We have actually, the [lingpy cookbook](http://github.com/lingpy/cookbook) where it is intended to add usage examples which will then also be listed from the lingpy.org homepage upon next release. I think using ipynb for this is just the easiest way, especially, since one can also render the notebooks in their original frame, like [this](https://render.githubusercontent.com/view/ipynb?commit=c026d5af36cef620f4d7cf6343affd847754bc02&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6c696e6770792f636f6f6b626f6f6b2f633032366435616633366365663632306634643763663633343361666664383437373534626330322f636f676e617465732d7061727469616c2d7374726963742d6c6f6f73652e6970796e62&nwo=lingpy%2Fcookbook&path=cognates-partial-strict-loose.ipynb&repository_id=47337578#Handling-Cognate-Sets:-Partial,-Strict,-and-Loose-Cognates-in-LingPy). 

I'll also try and add more examples in the future, and if you manage to even provide some initial tests, this would be even greater, as we have some coverage problems with MLN.

**Comment by Anaphory** [comment]
`ipynb` looks like the perfect format for it.
