### ISSUE TITLE
calign.align_pair can throw 

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#388]
When running partial cognate coding with LexStat on ASJP-soundclass data, I get a ZeroDivisionError:
```
2018-10-29 19:14:28,879 [INFO] Calculating random alignmentsfor pair rong1269/rong1269.
Traceback (most recent call last):                                                                                                                      
  File "/vol/home/kaipingga/databases/lexirumah-data/pylexirumah/autocode.py", line 119, in <module>
    args.soundclass, ratio_str))
  File "/vol/home/kaipingga/devel/lingpy/lingpy/compare/lexstat.py", line 286, in __init__
    conf=kw['conf'])
  File "/vol/home/kaipingga/devel/lingpy/lingpy/basic/wordlist.py", line 103, in __init__
    self, filename, row, col, conf or util.data_path('conf', 'wordlist.rc'))
  File "/vol/home/kaipingga/devel/lingpy/lingpy/basic/parser.py", line 432, in __init__
    QLCParser.__init__(self, filename, conf=conf)
  File "/vol/home/kaipingga/devel/lingpy/lingpy/basic/parser.py", line 72, in __init__
    raise IOError("Input file '{0}' does not exist.".format(filename))
OSError: Input file 'lexstats-asjp-5.tsv' does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/vol/home/kaipingga/databases/lexirumah-data/pylexirumah/autocode.py", line 124, in <module>
    lex.get_scorer(runs=10000)
  File "/vol/home/kaipingga/devel/lingpy/lingpy/compare/lexstat.py", line 1033, in get_scorer
    self._randist = self._get_randist(**kw)
  File "/vol/home/kaipingga/devel/lingpy/lingpy/compare/lexstat.py", line 861, in _get_randist
    kw['restricted_chars'])
  File "lingpy/algorithm/cython/calign.pyx", line 2772, in lingpy.algorithm.cython.calign.corrdist (lingpy/algorithm/cython/calign.c:28018)
ZeroDivisionError: float division by zero
```

In another run, it happened here:

```
Traceback (most recent call last):                                                                                                                      
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/vol/home/kaipingga/databases/lexirumah-data/pylexirumah/autocode.py", line 135, in <module>
    verbose=True)
  File "/vol/home/kaipingga/devel/lingpy/lingpy/compare/partial.py", line 426, in partial_cluster
    for concept, trace, matrix in matrices:
  File "/vol/home/kaipingga/devel/lingpy/lingpy/compare/partial.py", line 290, in _get_partial_matrices
    d = function(idxA, idxB, sliceA, sliceB)
  File "/vol/home/kaipingga/devel/lingpy/lingpy/compare/partial.py", line 243, in function
    return calign.align_pair(*args)[2]
  File "lingpy/algorithm/cython/calign.pyx", line 1614, in lingpy.algorithm.cython.calign.align_pair (lingpy/algorithm/cython/calign.c:15139)
ZeroDivisionError: float division
```

in that case, the offending forms were

    ['dhao1237', 'Papunesia', None, None, None, '1286', 'hot', Decimal('-8.226'), 'dhao1237', 'hot', 'Dhao', 'Austronesian, Malayo-Polynesian, Sumba-Hawu, Hawu-Dhao', 'dhao1237', Decimal('124.6683'), None, 'Sense perception', None, None, "sag'oro", ['gr08'], None, ['p/dhao'], None, 'HOT', ['s', 'a', 'ɠ', 'o', 'r', 'o'], 'nfa', 'panas', None, "sag'oro", 50780, 'saɠoro', [3, 7, 0, 7, 5, 7], 'AXBYBZ', 'sa0oro', '24', ['24.s.C', '24.a.V', '24.0.C', '24.o.V', '24.r.C', '24.o.V'], [2.0, 1.5, 1.75, 1.3, 1.75, 0.8], 0, 9528]

    ['sawi1256', 'Papunesia', None, None, None, '1286', 'hot', Decimal('-8.3433'), 'sawi1256', 'hot', 'Sawila', 'Timor-Alor-Pantar', 'sawi1256', Decimal('125.0922'), None, 'Sense perception', None, None, 'emala', ['datasets_swthc20151026sawilawordlistcheckedbymkandjiangjune2017_tsv'], None, [], None, 'HOT', ['e', 'm', 'a', 'l', 'a'], 'swt', 'panas', 'East Alor, Alor Regency, East Nusa Tenggara, Indonesia', None, 26064, 'emala', [7, 4, 7, 5, 7], 'XBYBZ', 'emala', '112', ['112.e.V', '112.m.C', '112.a.V', '112.l.C', '112.a.V'], [1.5, 1.75, 1.3, 1.75, 0.8], 0, 9561]

I will try to find out what's going on and fix it, although I'm really not a Cython expert.

**Comment by LinguList** [comment]
Please show the segments, and their form in sound classes. ZeroDivisionError usually is thrown when two elements are aligned in such a way that they don't have any similarity with themselves. This can only happen if you have one element of one sound only, that is not recognized by lingpy. But these are now usually captured by lexstat, as far as I know.

**Comment by LinguList** [comment]
Ah, here's your corrputed element: "sa0oro", the 0 indicates that the "ɠ" is non-standard, and in fact it isn't standard, it's some strange IPA that is not in use, as far as I know.

**Comment by LinguList** [comment]
Yes, but in general, you have all tools at hand, with ortho-profiles, etc., that you should be at a stage where you CAN take care of good data, right? There's a threshold when lexstat accepts that, and the general rule is to run lexstat before always with "check=True", so I think trying to trace this bug will consume a lot time that may be better spent on working towards cleaner data?

**Comment by Anaphory** [comment]
True.

Still, in this case, it should be remarked that I find no trace that `ɠ` is any less accepted than `ɓ` outside of LingPy. `ɠ` is in CLTS, in IPA, and in Cysouw&Moran. It is far rarer than `ɓ` in phoible, but it is attested. (I guess the fix in this specific cases is therefore to add `ɠ` to the existing sound class models?)

So it's little surprise that my CLTS-based checking and transforming infrastructure does not pick it up as a problem and should not, either; I need to actually ask LexStat to check to notice this.

**Comment by Anaphory** [comment]
Interestingly, the last of the implosives, `ʛ`, appears in Phoible never as such and [only once](https://phoible.org/parameters/051F53069ABAEA0FBFD98E410052886C#6/15.661/268.337) as a de-voiced/voiceless implosive.

**Comment by LinguList** [comment]
Yes, the other one is useful as well, to avoid future problems, thanks in advance!
