### ISSUE TITLE
update LexStat tutorial

### ISSUE THREAD

**Issue by martino-vic** [lingpy/lingpy#446]
Installing the latest lingpy version and following the tutorial at https://lingpy.org/tutorial/workflow.html:

```
>>> from lingpy import *
>>> lex = LexStat('test_data/KSL.qlc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/viktor/Documents/lexstat/venv/lib/python3.8/site-packages/lingpy/compare/lexstat.py", line 293, in __init__
    Wordlist.__init__(
  File "/home/viktor/Documents/lexstat/venv/lib/python3.8/site-packages/lingpy/basic/wordlist.py", line 97, in __init__
    QLCParserWithRowsAndCols.__init__(
  File "/home/viktor/Documents/lexstat/venv/lib/python3.8/site-packages/lingpy/basic/parser.py", line 396, in __init__
    QLCParser.__init__(self, filename, conf=conf)
  File "/home/viktor/Documents/lexstat/venv/lib/python3.8/site-packages/lingpy/basic/parser.py", line 87, in __init__
    raise IOError("Input file '{0}' does not exist.".format(filename))
OSError: Input file 'test_data/KSL.qlc' does not exist.
```

**Comment by martino-vic** [comment]
sorry my bad just realsed I have to clone the repo from github and go into the test folder

**Comment by LinguList** [comment]
There's a command that is called "test_data", in tests, if I remember properly, with this, you can access the data from everywhere. I recommend, however, to read our more recent workflows. E.g. the one [here](https://doi.org/10.1093/jole/lzy006), but it also depends on what specifically you want to do.
